version: '3.1'
services:
  nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - ${PWD}/_docker/nginx/nginx-test.template:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - timber_client
      - timber_api

  timber_client:
    image: timber-client
    container_name: timber_client
    restart: always
    depends_on:
      - timber_api

  timber_api:
    image: timber-api
    container_name: timber_api
    environment:
      - NODE_ENV=production
